### PR TITLE
fixed DELETE not working

### LINKED ISSUE #32: DELETE integration does not work
there are several differences between the setup of ADD and DELETE that might be the culprit, notably I don't see api key being passed at all (maybe it's in a helper?)

### PR DESCRIPTION
**Pull request by jgrayson676**
fix #32

### CODE REVIEW

File: src/delete_item.coffee [hunk 1]
```diff
@@ -4,9 +4,10 @@ helper = require('./helper')
 request = (vars) ->
   values = helper.getValues vars
 
-  url: "https://app.suppressionlist.com/lists/#{vars.list_id}/items/#{vars.values}"
+  url: "https://app.suppressionlist.com/lists/#{vars.list_id}/items"
   method: 'DELETE'
   headers: helper.getRequestHeaders()
```
Comment (cgrayson) [inline src/delete_item.coffee]: I think Zalary probably right, in #32, about this also being a problem.
