### PR TITLE
fixed validate in ADD and DELETE

### LINKED ISSUE #36: When the value to be queried is blank, skip the integration

### PR DESCRIPTION
**Pull request by jgrayson676**
fix #36

### CODE REVIEW

File: spec/add_item_spec.coffee [hunk 1]
```diff
@@ -102,3 +102,7 @@ describe 'Add List Item', ->
           reason: 'SuppressionList error (500) Possibly incorrect list_id'
       response = integration.response(vars, req, res)
       assert.deepEqual expected, response
+
+  describe 'Validate', ->
+    it 'validate should function properly', ->
```
Comment (cgrayson) [inline spec/add_item_spec.coffee]: Minor, but ideally `describe()` + `it()` strings should read like a sentence in the output: "Validate … should function properly".

**Comment by cgrayson** [comment]
Otherwise LGTM
